spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kme
    username: root
    password: #removed
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
  mvc:
    format:
      time: HH:mm:ss
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /**
    resources:
      chain:
        strategy:
          content:
            mime-types:
              js: application/javascript
  security:
    user:
      name: olala
      password: #removed
  sql:
    init:
      data-locations: classpath:import.sql
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: szugajew.esthetic@gmail.com
    password: #removed
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#            required: true
  logging:
    level:
      org:
        springframework:
          security: DEBUG

  google:
    client:
      client-id: #removed
      client-secret: #removed

