spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kme
    username: root
    password: coderslab
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  security:
    user:
      name: olala
      password: prosiaczek
  sql:
    init:
      data-locations: classpath:import.sql



